version: '3'

services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
      args:
        - UID=$UID
        - GID=$GID
    environment:
      DOCKER_HOST: "tcp://docker:2375"
    depends_on:
      - docker
    volumes:
      - .:/home/vscode/workspace
      - ./cache/cargo-registry:/usr/local/cargo/registry

  docker:
    image: docker:20.10.9-dind
    privileged: true
    command: ["dockerd", "--host=tcp://0.0.0.0:2375"]

  # Production version of container
  simple-faas:
    build:
      dockerfile: docker/simple-faas/Dockerfile
      context: .
    depends_on:
      - docker
