[package]
name = "simple-faas"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
env_logger = "0.9.0"
log = "0.4.16"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
